name: dandelion
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- pandas
- pandoc
- pyyaml
- changeo
- seaborn
- statsmodels
- numba
- pytables
- pytest
- pip
- tbb
- pip:
  - nbsphinx
  - sphinx-autodoc-typehints
  - annoy==1.16.3
  - rpy2==3.4.2
  - pytest-cov
  - -r requirements.txt
  - git+https://www.github.com/zktuong/nxviz.git; python_version < '3.10'
  - nxviz==0.7.4; python_version >= '3.10'
  - scirpy
  - scrublet