{% set name = "dandelion" %}
{% set version = "0.0.1" %}

package:
  name: dandelion
  version: "0.0.1"

source:
  git_rev: 0.0.1
  git_url: https://github.com/zktuong/dandelion.git

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas    
    - anndata
    - scanpy
    - changeo
    - dandelion
    - changeo
    - anndata
    - scanpy
    - scrublet
    - scikit-learn
    - scipy
    - numba
    - seaborn
    - python-igraph
    - networkx
    - leidenalg
  run:
    - python 3.7
    - numpy 1.18.4
    - pandas 1.0.3
    - changeo 1.0.0
    - anndata 0.7.1
    - scanpy 1.4.6
    - scrublet 0.2.1
    - python-Levenshtein 0.12.0
    - distance 0.1.3
    - joblib 0.14.1
    - jupyter 1.0.0
    - scipy 1.4.1
    - numba 0.48.0
    - seaborn 0.10.1
    - python-igraph 0.8.2
    - leidenalg 0.8.0
    - networkx 2.4

about:
  home: https://github.com/zktuong/dandelion
  license: agpl-3.0
  license_family: agpl-3.0
  summary: dandelion, a sc-BCRseq analysis tool