name: dandelion
channels:
- conda-forge
- bioconda
- anaconda
- defaults
dependencies:
- python=3.7
- numpy
- pandas
- pandoc
- pyyaml
- changeo
- adjustText
- distance
- joblib
- plotnine
- pip
- pip:
  - sc-dandelion
  - sphinx
  - nbsphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - recommonmark
