name: dandelion
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- numpy
- pandas
- pandoc
- pip
- yaml
- pip:
  - sc-dandelion
  - sphinx
  - nbsphinx
  - sphinx-rtd-theme
  - sphinx-autodoc-typehints
  - recommonmark
