name: dandelion
channels:
- conda-forge
- defaults
- bioconda
- r
dependencies:
- python=3.7
- seaborn
- scikit-learn
- statsmodels
- pip
- setuptools
- pycodestyle
- pydocstyle
- pandoc
- numba
- pytables
- numpy
- pandas
- python-igraph
- leidenalg
- sphinx
- distance
- joblib
- plotnine
- adjustText
- rpy2>=3.3.2,<3.3.5
- pip:
    - scanpy
    - recommonmark
    - nbsphinx
    - sphinx-rtd-theme
    - sphinx-autodoc-typehints
