name: Create badge

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  badge_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - id: version
        run: echo "##[set-output name=version;]$(python dandelion/version.py)"
      - name: version badge
        uses: RubbaBoy/BYOB@v1.2.0
        with:
          NAME: github
          LABEL: 'GitHub'
          ICON: 'github'
          STATUS: ${{ steps.date.outputs.version}}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}