name: R-tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

env:  
  cache-version: 'cache-v1'

jobs:
  R-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
        python-version: [3.7, 3.8]        
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      NOT_CRAN: true
      TZ: UTC
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        auto-activate-base: true
        auto-update-conda : true
        activate-environment: dandelion
        channels: conda-forge, bioconda, anaconda, defaults
        channel-priority: true
        python-version: ${{ matrix.python-version }}
    - run: |
        conda install libcurl
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
          r-version: release

    - name: Setup pandoc from r-lib
      if: matrix.os != 'ubuntu-latest'
      uses: r-lib/actions/setup-pandoc@master

    - name: install R dependencies
      run: |
        install.packages(c('RCurl'))
      shell: Rscript {0}
    - name: Test if R dependencies are installed properly
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        command: |
          Rscript tests/r_dependencies.R
        on_retry_command: |
          Rscript tests/r_install.R

    - name: Cache R packages
      if: "!contains(github.event.head_commit.message, '/nocache') && matrix.os != 'ubuntu-latest'"
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-

    - name: Cache R packages on ubuntu-latest
      if: "!contains(github.event.head_commit.message, '/nocache') && matrix.os == 'ubuntu-latest' "
      uses: actions/cache@v2
      with:
        path: /home/runner/work/_temp/Library
        key: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-

