name: R-tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  R-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]
        r: release
        bioc: 3.12        
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      NOT_CRAN: true
      TZ: UTC
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r }}
    - name: install R dependencies
      run: |
        install.packages(c('remotes','RCur','XML'))
        remotes::install_cran("BiocManager")
        BiocManager::install(version = "${{ matrix.bioc }}", ask = FALSE)
        BiocManager::install(c('Biostrings', 'GenomicAlignments', 'IRanges'))
        install.packages(c('remotes','shazam', 'alakazam', 'tigger', 'airr', 'optparse'))        
      shell: Rscript {0}        
    - name: Test if R dependencies are installed properly
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        command: |
          Rscript tests/r_dependencies.R
        on_retry_command: |
          Rscript tests/r_install.R