name: Testing package using Miniconda

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"
  schedule:
    # Note that cronjobs run on master/main by default
    - cron: "0 0 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install macOS system dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install cairo pkg-config autoconf automake libtool
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        auto-update-conda : true
        activate-environment: dandelion
        channels: conda-forge, bioconda, defaults
        channel-priority: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name dandelion
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
        
  caching:
    name: Caching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('docs/environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dandelion
          channel-priority: strict
          environment-file: docs/environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
