name: R-tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

env:  
  cache-version: 'cache-v1'

jobs:
  R-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]        
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      NOT_CRAN: true
      TZ: UTC
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2    
    - name: Install ubuntu system dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libcurl4-openssl-dev
        sysreqs=$(Rscript -e 'cat("apt-get update -y && apt-get install -y", paste(gsub("apt-get install -y ", "", remotes::system_requirements("ubuntu", "20.04")), collapse = " "))')
        echo $sysreqs
        sudo -s eval "$sysreqs"
    
    - name: Install macos system dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install cairo pkg-config autoconf automake libtool
        ## Enable installing XML from source if needed
        brew install libxml2 imagemagick@6 harfbuzz fribidi libgit2
        echo "XML_CONFIG=/usr/local/opt/libxml2/bin/xml2-config" >> $GITHUB_ENV        
    
    - name: Install windows system dependencies
      if: matrix.os == 'windows-latest'
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        cmd: choco install curl

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
          r-version: release

    - name: Setup pandoc from r-lib
      if: matrix.os != 'ubuntu-latest'
      uses: r-lib/actions/setup-pandoc@master

    - name: install R dependencies
      run: |
        install.packages(c('remotes','RCurl','XML'))
        remotes::install_cran("BiocManager")
        BiocManager::install(version = "3.12", ask = FALSE)
        BiocManager::install(c('Biostrings', 'GenomicAlignments', 'IRanges'))
        install.packages(c('shazam', 'alakazam', 'tigger', 'airr', 'optparse'))
      shell: Rscript {0}
    - name: Test if R dependencies are installed properly
      uses: nick-invision/retry@v2
      with:
        timeout_seconds: 15
        max_attempts: 3
        command: |
          Rscript tests/r_dependencies.R
        on_retry_command: |
          Rscript tests/r_install.R

    - name: Cache R packages
      if: "!contains(github.event.head_commit.message, '/nocache') && matrix.os != 'ubuntu-latest'"
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-

    - name: Cache R packages on ubuntu-latest
      if: "!contains(github.event.head_commit.message, '/nocache') && matrix.os == 'ubuntu-latest' "
      uses: actions/cache@v2
      with:
        path: /home/runner/work/_temp/Library
        key: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ env.cache-version }}-${{ matrix.os }}-biocversion-RELEASE_3_12-r-4.0-

