name: Testing dandalion package using Miniconda

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install macOS system dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install cairo pkg-config autoconf automake libtool
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        auto-update-conda : true
        activate-environment: dandelion
        channels: conda-forge, bioconda, anaconda, defaults
        channel-priority: true
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        conda env update --file docs/environment.yml --name dandelion    
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
    - name: Test initializing Dandelion class
      run: |
        python tests/IO_test.py
  caching:
    name: Caching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/example-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('docs/environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda : true
          activate-environment: dandelion
          channels: conda-forge, bioconda, anaconda, defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          environment-file: docs/environment.yml
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
